esphome:
  name: eplantalk02
  friendly_name: ePlantalk 02
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: esp-idf

# 안정성 관련
logger:
  level: WARN
# Enable logging
# logger:
#   hardware_uart: USB_SERIAL_JTAG
#   level: DEBUG

api:
  reboot_timeout: 0s

# interval:
#   - interval: 60s
#     then:
#       - lambda: |-
#           wifi_sta_list_t station_list;
#           if (esp_wifi_ap_get_sta_list(&station_list) == ESP_OK) {
#             if (station_list.num == 0) {
#               ESP_LOGW("ap_watchdog", "No clients connected. Restarting...");
#               esp_restart();
#             }
#           }



wifi:
  ap:
    ssid: "ePlantalk02"
    password: "12345678"
    channel: 1       # 1 6 11 1 6 번갈아
    ap_timeout: 0s   # 항상 AP 유지

  power_save_mode: none
  output_power: 9dB  #8~12dBm 권장, Full: 20

  manual_ip:
    static_ip: 192.168.4.1
    gateway: 192.168.4.1
    subnet: 255.255.255.0


web_server:
  port: 80
  version: 3
  include_internal: true
  local: true

sensor:
  - platform: adc
    pin: GPIO3
    name: "moisture"
    id: moisture_sensor
    attenuation: 12db
    update_interval: 5s
    filters:
      - sliding_window_moving_average:
          window_size: 10
          send_every: 1

  - platform: adc
    pin: GPIO1
    name: "light"
    id: light_sensor
    attenuation: 12db
    update_interval: 5s
    filters:
      - sliding_window_moving_average:
          window_size: 10
          send_every: 1

# JSON 통합 엔드포인트
# text_sensor:
#   - platform: template
#     name: "Sensors JSON"
#     id: sensors_json
#     update_interval: 10s
#     lambda: |-
#       char buffer[128];
#       snprintf(buffer, sizeof(buffer),
#         "{\"moisture\": %.3f, \"light\": %.3f}",
#         id(moisture_sensor).state,
#         id(light_sensor).state);
#       return std::string(buffer);

